# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/trusty64"
  config.vm.box = "generic/ubuntu1804"
  
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = "2"
  end

  if ENV['PROVISION_INFRA'] != 'false'
    config.vm.provision :shell, :path => "prerequisites.sh"
    if ENV['K8S_VERSION'] == '1.17'
      config.vm.provision :shell, :path => "install-k8s-1.17.sh"
    else
      config.vm.provision :shell, :path => "install-k8s-latest.sh"
    end
    config.vm.provision :shell, :path => "configure-last-k8s-steps.sh"
  end
end
